# Generated by Django 5.1.6 on 2025-02-22 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_id', models.CharField(blank=True, db_column='mark-id', max_length=100, null=True)),
                ('mark_name', models.CharField(blank=True, db_column='mark-name', max_length=100, null=True)),
                ('mark_cyrillic_name', models.CharField(blank=True, db_column='mark-cyrillic-name', max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('model_id', models.CharField(blank=True, db_column='model-id', max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, db_column='model-name', max_length=100, null=True)),
                ('model_cyrillic_name', models.CharField(blank=True, db_column='model-cyrillic-name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ads_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ads.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField(help_text='Пробег в км')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold')], default='pending', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.carbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
