# Generated by Django 5.1.6 on 2025-02-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_carsdatatest_remove_carmodel_brand_alter_ad_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='brand',
            new_name='mark_names',
        ),
    ]
