# Generated by Django 5.1.6 on 2025-03-04 18:34

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ad_image_adimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to='ads/', validators=[ads.models.validate_image]),
        ),
    ]
