# Generated by Django 5.1.6 on 2025-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_adimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='source',
            field=models.CharField(default='web', max_length=3),
        ),
    ]
