# Generated by Django 5.1.6 on 2025-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ad_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, default='+78000001234', max_length=20, null=True),
        ),
    ]
