# Generated by Django 5.1.6 on 2025-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_profile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], default='petrol', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
