# Generated by Django 5.1.6 on 2025-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_ad_fuel_type_alter_profile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='gearbox',
            field=models.CharField(choices=[('automatic', 'Автомат'), ('machanical', 'Механика')], default='machanical', max_length=10),
        ),
    ]
