# Generated by Django 5.1.6 on 2025-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_ad_gearbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('suv', 'Внедорожник'), ('station_wagon', 'Универсал'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('limousine', 'Лимузин'), ('van', 'Фургон'), ('convertible', 'Кабриолет')], default='sedan', max_length=15),
        ),
    ]
