# Generated by Django 5.1.6 on 2025-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='exchange',
            field=models.BooleanField(default=False, help_text='Отметьте, если хотите обмен авто', verbose_name='Обмен'),
        ),
    ]
