# Generated by Django 5.1.6 on 2025-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_ad_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='drive',
            field=models.CharField(choices=[('front', 'Передний'), ('rear', 'Задний'), ('4x4', 'Полный')], default='front', max_length=7),
        ),
    ]
