# Generated by Django 5.1.6 on 2025-04-04 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_ad_country_ad_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
