# Generated by Django 5.1.6 on 2025-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramad',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
