# Generated by Django 5.1.6 on 2025-03-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0002_alter_telegramad_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramad',
            name='photo_url',
        ),
        migrations.CreateModel(
            name='TelegramAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='telegramm_parse.telegramad')),
            ],
        ),
    ]
