# Generated by Django 5.1.6 on 2025-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0003_remove_telegramad_photo_url_telegramadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
