# Generated by Django 5.1.6 on 2025-03-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0004_telegramad_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramad',
            old_name='brand',
            new_name='mark_names',
        ),
    ]
