# Generated by Django 5.1.6 on 2025-03-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0005_rename_brand_telegramad_mark_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramad',
            old_name='text',
            new_name='description',
        ),
    ]
