# Generated by Django 5.1.6 on 2025-03-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0006_rename_text_telegramad_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramadimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
