# Generated by Django 5.1.6 on 2025-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0007_rename_image_url_telegramadimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='source',
            field=models.CharField(default='telegram', max_length=8),
        ),
    ]
