# Generated by Django 5.1.6 on 2025-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0008_telegramad_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
