# Generated by Django 5.1.6 on 2025-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0009_telegramad_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], default='petrol', max_length=10, null=True, verbose_name='Любое топливо'),
        ),
    ]
