# Generated by Django 5.1.6 on 2025-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0010_telegramad_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='gearbox',
            field=models.CharField(choices=[('automatic', 'Автомат'), ('machanical', 'Механика')], default='machanical', max_length=10),
        ),
    ]
