# Generated by Django 5.1.6 on 2025-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0013_telegramad_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='seller',
            field=models.CharField(choices=[('private', 'Частник'), ('company', 'Компания')], default='private', max_length=7),
        ),
    ]
