# Generated by Django 5.1.6 on 2025-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0015_telegramad_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold')], default='pending', max_length=10),
        ),
    ]
