# Generated by Django 5.1.6 on 2025-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0016_telegramad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramad',
            name='color',
            field=models.CharField(choices=[('black', 'Черный'), ('gray', 'Серый'), ('white', 'Белый'), ('blue', 'Синий'), ('red', 'Красный'), ('green', 'Зеленый'), ('orange', 'Оранжевый'), ('yellow', 'Желтый')], default='white', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='telegramad',
            name='damaged',
            field=models.CharField(choices=[('ok', 'Целая/На ходу'), ('damaged', 'Битая/Не на ходу')], default='ok', max_length=10, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='telegramad',
            name='location',
            field=models.CharField(blank=True, choices=[('in_stock', 'В наличии'), ('in_transit', 'В пути'), ('on_order', 'Под заказ')], default='in_stock', max_length=10, verbose_name='Статус наличия'),
        ),
        migrations.AddField(
            model_name='telegramad',
            name='steering',
            field=models.CharField(choices=[('left', 'Левый'), ('right', 'Правый')], default='left', max_length=5, verbose_name='Руль'),
        ),
    ]
