# Generated by Django 5.1.6 on 2025-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm_parse', '0018_telegramad_country_telegramad_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadimage',
            name='image',
            field=models.ImageField(upload_to='ads/'),
        ),
    ]
